# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6701832384e67fcdeb39991b182734ebd52976a1da89485795c3fe17a31d5b8477082fa1dfe4fbc5dde79206ff314f3513f609c2e61acc9b57a7605fbfd48a46

test:
  secret_key_base: 3a279b15b0745b7c8667b979cea4dd9933d7173e4b8d93fd75efbe4891b324fb80a7f1d582fae623c8dd7181a991c10a967806932938fdd410e35c8c59f60ab5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
